env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
rules: {
  "no-param-reassign": 0,
  "max-len": "off",
  "react/prop-types": "off",
  "no-console": "off",
  "no-alert": "off",
  "no-unused-vars": "off",
  "react/no-danger": "off",
  "no-restricted-globals": "off",
}
